# Generated by Django 5.1.2 on 2024-11-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzableData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Entity', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('Name_type', models.CharField(max_length=255)),
                ('Date_ofBirth', models.CharField(max_length=255)),
                ('place_of_birth', models.TextField()),
                ('citizenship', models.CharField(max_length=255)),
                ('adress', models.TextField(max_length=255)),
                ('Additional_information', models.TextField()),
                ('listing_information', models.TextField()),
                ('Commities', models.CharField(max_length=255)),
                ('Control_Date', models.DateField(blank=True, null=True)),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzableData', to='analysis_app.analysissummary')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('count', models.IntegerField()),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='analysis_app.analysissummary')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_Issue', models.DateField(null=True)),
                ('Validity', models.DateField(null=True)),
                ('Order_Number_Hebrew', models.TextField(null=True)),
                ('Order_Number_English', models.TextField(null=True)),
                ('Row', models.IntegerField(null=True)),
                ('Full_Name_Hebrew', models.TextField(null=True)),
                ('Full_name_English', models.TextField(null=True)),
                ('Full_name_Arabic', models.TextField(null=True)),
                ('AKA_Hebrew', models.TextField(null=True)),
                ('Nickname_Hebrew', models.TextField(null=True)),
                ('AKA_English', models.TextField(null=True)),
                ('Nickname_English', models.TextField(null=True)),
                ('Identification_Number', models.TextField(null=True)),
                ('Company_Registration_Number', models.TextField(null=True)),
                ('DOB', models.DateField(null=True)),
                ('Street_1_Hebrew', models.TextField(null=True)),
                ('Street_1_English', models.TextField(null=True)),
                ('Street_2_Hebrew', models.TextField(null=True)),
                ('Street_2_English', models.TextField(null=True)),
                ('Building_Number', models.TextField(null=True)),
                ('Floor', models.TextField(null=True)),
                ('City_Hebrew', models.TextField(null=True)),
                ('City_English', models.TextField(null=True)),
                ('Country_Hebrew', models.TextField(null=True)),
                ('Country_English', models.TextField(null=True)),
                ('Postal_Code', models.IntegerField(null=True)),
                ('Phone_Number_1', models.TextField(null=True)),
                ('Phone_Number_2', models.TextField(null=True)),
                ('Email_1', models.TextField(null=True)),
                ('Email_2', models.TextField(null=True)),
                ('Organizational_Affiliation_Hebrew', models.TextField(null=True)),
                ('Organizational_Affiliation_English', models.TextField(null=True)),
                ('Seizure_Amount', models.TextField(null=True)),
                ('Reason_Hebrew', models.TextField(null=True)),
                ('Reason_English', models.TextField(null=True)),
                ('bank_account_hebrew', models.TextField(null=True)),
                ('bank_account_english', models.TextField(null=True)),
                ('LastPrinted', models.DateTimeField(null=True)),
                ('Created', models.DateTimeField(null=True)),
                ('LastSaved', models.DateTimeField(null=True)),
                ('Version', models.FloatField(null=True)),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='analysis_app.analysissummary')),
            ],
        ),
    ]
