# Generated by Django 4.2.1 on 2024-11-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('count', models.IntegerField()),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='analysis_app.analysissummary')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzableData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Entity', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('Name_type', models.CharField(max_length=255)),
                ('Date_ofBirth', models.CharField(max_length=255)),
                ('place_of_birth', models.TextField()),
                ('citizenship', models.CharField(max_length=255)),
                ('adress', models.TextField(max_length=255)),
                ('Additional_information', models.TextField()),
                ('listing_information', models.TextField()),
                ('Commities', models.CharField(max_length=255)),
                ('Control_Date', models.DateField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnalyzableData', to='analysis_app.analysissummary')),
            ],
        ),
    ]
