# Generated by Django 5.1.2 on 2024-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzabledata',
            name='adress',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
