# Generated by Django 5.1.2 on 2024-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0002_alter_analyzabledata_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzabledata',
            name='Additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='Commities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='Date_ofBirth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='Name_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='citizenship',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='listing_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='place_of_birth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analyzabledata',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
